### ISSUE TITLE
wut?

### ISSUE THREAD

**Issue by PocketKiller** [MCrafterss/Mwebsite#1]
what's this?

**Comment by CraftingMania** [comment]
this is a website for mcrafters i am modifing legends of mcpe website to be mcrafters and i will connect all our projects with the website and i will change it

**Comment by CraftingMania** [comment]
wait i wont modify i will make mine

**Comment by CraftingMania** [comment]
i mean our

**Comment by NawafCraft** [comment]
Gays I Want To Make RikLab:|
